### ISSUE TITLE
For UI improvement; scrolling horizontally is needed

### ISSUE THREAD

**Issue by abdev2019** [mukuljainx/Mokku#108]
UI is blocked; could not scroll horizontally.

![image](https://user-images.githubusercontent.com/42867869/234123602-725703e8-8f5c-43b0-bc54-609d44da4590.png)

**Comment by mukuljainx** [comment]
Thanks for bringing attention to this, working on a new version should solve these issues.

**Comment by mukuljainx** [comment]
Added in V2
