### ISSUE TITLE
optimization suggestion

### ISSUE THREAD

**Issue by xyabc120** [mukuljainx/Mokku#112]
#### optimization suggestion
- Even if the scroll bar is pulled to the end, the text will be blocked
-  the content in JSON format cannot wrap
-  and JSON formatting support
- the left and right panels support layout size settings
- "`Mokku not available on this url`" error when DevTools is undocked into separate window

![image](https://github.com/mukuljainx/Mokku/assets/14323465/bdcdcafc-d88c-4a82-aa84-9c4c1c4d84f9)

**Comment by mukuljainx** [comment]
Hi @xyabc120 , 

I am working on a new version of Mokku, it should solve most UI issues.

**Comment by mukuljainx** [comment]
> "Mokku not available on this url" error when DevTools is undocked into a separate window

Will see what can be done for this, first priority is to re-write as the current codebase is too complicated to do anything.

**Comment by mukuljainx** [comment]
This should work after 2.0.4, if there is one active window only, Mokku will load for it! If there are 2 or more, Mokku will ask which one you want to mock

**Comment by xyabc120** [comment]
Very good, version 2.0.1 has already solved most of my problems
