### ISSUE TITLE
Chrome throws warnings for every page

### ISSUE THREAD

**Issue by MW-Hochmann** [mukuljainx/Mokku#114]
When I have the extension enabled and open any page (I tried with StackOverflow and GitHub) I get the following warning:

`panel.js:90 Uncaught Error: Couldn't find a style target. This probably means that the value for the 'insert' parameter is invalid.`

**Comment by mukuljainx** [comment]
Thanks for reporting, it has been fixed, will be released soon.

**Comment by mukuljainx** [comment]
Fixed with 2.0.0
