### ISSUE TITLE
Feat: Support Import & Exports of mocks

### ISSUE THREAD

**Issue by mukuljainx** [mukuljainx/Mokku#15]

**Comment by ledeneveugene** [comment]
I also need it.

**Comment by mukuljainx** [comment]
Hi @ledeneveugene, Unfortunately, I can't preserve data on uninstall as chrome clears everything, I am picking up these features for the next release.

Would you be interested in cloud-based storage, mocks & email (for identification/authentication)? You will also able to share mocks and edit mocks for other users.

**Comment by ledeneveugene** [comment]
> Hi @ledeneveugene, Unfortunately, I can't preserve data on uninstall as chrome clears everything, 
I thought that it is impossible, but I hoped that I am wrong.

> I am picking up these features for the next release.
That's great!

> Would you be interested in cloud-based storage, mocks & email (for identification/authentication)? You will also able to share mocks and edit mocks for other users.
Yes, I guess it will be very useful features. Thank you for your work!

**Comment by mukuljainx** [comment]
mukuljainx@81f279a10c753c8976c4446bcf84352e30a48ec7

Hi, while the dashboard (cloud-based) will take some time, but export imports should work from 1.4.0.

**Comment by yarkovaleksei** [comment]
Thanks )
