### ISSUE TITLE
Feat: Add capability to add headers 

### ISSUE THREAD

**Issue by manne** [mukuljainx/Mokku#20]
I want to add headers, so the 201 response has got the `Location` header

**Comment by mukuljainx** [comment]
Added in [feat(mock): customize headers & view req/response header in logs](https://github.com/mukuljainx/Mokku/commit/013660c93dda66851a9609b07421521e465bb6ce)

Build: https://github.com/mukuljainx/Mokku/blob/master/mokku.zip

Will be available in the chrome store in 2-3 days (v1.0.6)
