### ISSUE TITLE
Ability to mock requests by mask

### ISSUE THREAD

**Issue by orihomie** [mukuljainx/Mokku#25]
Is there any ability to mock http requests by url mask or, more complex case, post request body mask?

**Comment by mukuljainx** [comment]
Hi,

What do you mean by URL mask, can you provide an example?

**Comment by orihomie** [comment]
I mean instead of using 
> /somepath/somesubpath/route

to make available this:

> /somepath/*/route

It's an example, mask could be regex or just globs 🤷‍♂️

**Comment by mukuljainx** [comment]
Hi, please checkout

https://github.com/mukuljainx/Mokku/releases/tag/v1.1.0

> /somepath/*/route

will not work instead use 

> /somepath/(.*)/route

The build has been submitted for review in Chrome store but that might take some time as their policy has changed. You can use mokku.zip from the repo and load it as an external extension.
