### ISSUE TITLE
The Ability to Prettify Response JSON

### ISSUE THREAD

**Issue by ipenywis** [mukuljainx/Mokku#37]
Right Now if you copy/paste the JSON from one of the responses on the Network tab to the Mocku response JSON it would look pretty ugly and you won't be able to edit it or view it properly.

**Solution**: Add a simple button or auto prettifying when the JSON is pasted.

**Comment by mukuljainx** [comment]
Hi @ipenywis, sure this will be a nice feature to have, will add it in the next release along with exports.

**Comment by mukuljainx** [comment]
mukujainx@5e54bc7b2eee00f833c642553c1af4f7a9f9a58d

Closing the issue, but it will take around 2 days to get approved at store.
