### ISSUE TITLE
Feat: Add duplicate button

### ISSUE THREAD

**Issue by yarkovaleksei** [mukuljainx/Mokku#39]
Please, add duplicate button to list item.

It so happens that the mocks are not very different. And it's easier to duplicate and modify one property than create a new one.

**Comment by mukuljainx** [comment]
Hi @yarkovaleksei, sounds useful, sure.

**Comment by mukuljainx** [comment]
#7a6c55e5ab64a18a308c9fe59c0fe90b61d5045d

**Comment by yarkovaleksei** [comment]
Thanks )
