### ISSUE TITLE
FormData class is redefined

### ISSUE THREAD

**Issue by xorxsan** [mukuljainx/Mokku#40]
Hi,

   when Mokku is enabled, the [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) class gets redefined as this:
```
> const formData = new FormData(<a form with values>)
> formData
g {fd: FormData, form: form.standard-form, append: ƒ}
append: ƒ ()
fd: FormData {}
form: form.standard-form
entries: (...)
get entries: ƒ ()
__proto__: Object
```
And doing any operations on that variable like `formData.get("")` throws an exception:
```
TypeError: formData.get is not a function
```

Tried it in Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by mukuljainx** [comment]
Hi @xorxsan, thanks for reporting, will look into it.

**Comment by mukuljainx** [comment]
Hi @xorxsan just an update, this is not very straight forward as I am using a library `xhook` that does, I exploring new ways to mock which take page injection out of context, no injection no unexpected modification like if it works then well and good, if not I will try to inject getter and setters to current form data class.

**Comment by mukuljainx** [comment]
Hi @xorxsan,  Can you check this again, I checked with 2.0.0(1), not happening anymore. Feel free to reopen.
