### ISSUE TITLE
Add description field

### ISSUE THREAD

**Issue by KyryloKuchuk** [mukuljainx/Mokku#47]
It would be great if be able to add a description to the mocked API.
It helps to navigate in the case when you have a few same mocked API but with different responses.

**Comment by mukuljainx** [comment]
Hi, thanks for raising this, seems like a good use case, currently there is a no good way to do it, one is to have `:id` sort of params in URL through which you can identify the mock response they can work as tags. For eg.

`some\cool\end\point\` you want this with 2 response 200 & 201 (or they can have different bodies), what you can do add two mocks as 

1. `:some_200\cool\end\point\`
2. `:some_201\cool\end\point\`

this translates to `.*\cool\end\point\`, 1 should be enabled at a time as they are the same URLs.

Let me know if this works or you need help with something else.

I will start working on all pending feature/bugs from probably next month, occupied with a lot of things right now.
P.S.: A full page is coming too.

**Comment by KyryloKuchuk** [comment]
Unfortunately, it doesn't work for me. 
My site sends requests to the same address but with specifying a port for example https://mysite.com:8080/api/myApi
I tried next cases:
   :test1https://mysite.com:8080/api/myApi
   :test1/https://mysite.com:8080/api/myApi
   :test1/api/myApi
 Only exact match work for me  https://mysite.com:8080/api/myApi

**Comment by mukuljainx** [comment]
Can you try?
`https://mysite.com:8080/:test1/myApi`
`https://mysite.com:8080/:test2/myApi`

**Comment by KyryloKuchuk** [comment]
In case enable only one rule  syntax **:id** work, but, it's not the best solution , becouse if app sends api requests to pagination for example:
https://mysite.com:8080/myApi1/1/10
https://mysite.com:8080/myApi2/1/10
The rule https://mysite.com:8080/:test1/1/10  find two requests and it would be error

In case enable two, there work first one:
(active) https://mysite.com:8080/:test1/myApi
(active) https://mysite.com:8080/:test2/myApi

In case disable first and enable second, mock doesn't work::
(inactive) https://mysite.com:8080/:test1/myApi
(active) https://mysite.com:8080/:test2/myApi

**Comment by mukuljainx** [comment]
yup in this case that hack will not work, I will try to add tags this weekend.

**Comment by KyryloKuchuk** [comment]
Thanks

**Comment by Julioevm** [comment]
Hey great work with the extension, very handy! It would be great if we could have this, i'm not able to have two mocks for the same endpoint and I have to check several things on the same endpoint which makes it very tedios work otherwise!

**Comment by mukuljainx** [comment]
Hi,

Seems like this feature is in demand ( 2 people are enough for me at this stage 😅), this will be done this weekend. Along with the description, there will be tags too.

**Comment by mukuljainx** [comment]
Hi @KyryloKuchuk & @Julioevm,

This feature has been added soon it will available in the Chrome Store as [v1.7.0](https://github.com/mukuljainx/Mokku/releases/tag/v1.7.0).

Now you can add/edit the description and it will be available as a tooltip in the mocks list with the `info` icon.
You can also add multiple endpoints with the same method, but only one can be enabled at a time.


![image](https://user-images.githubusercontent.com/10228876/132951822-0c32e2ca-8c97-417a-951e-c4d0ff5cbc42.png)
<img width="656" alt="Screenshot 2021-09-11 at 8 17 52 PM" src="https://user-images.githubusercontent.com/10228876/132951772-b2bcc334-c8e6-4ecc-a06b-82911e5a307b.png">

**Comment by mukuljainx** [comment]
Added name as well in v2.0.0, which is also visible in Mock table.
