### ISSUE TITLE
Request body while Creating new Mock

### ISSUE THREAD

**Issue by ShykulaD** [mukuljainx/Mokku#48]
Hi, I want to CreatE new mock (not from logged requests), how can I do this? 
Did find this feature...

**Comment by mukuljainx** [comment]
Hi, to create a mock you can click `create mock` on top left, its the 3rd actionable button from the left. Let me know if it works.

**Comment by ShykulaD** [comment]
Yep, but how can I add Request body to my POST request?

**Comment by ShykulaD** [comment]
I see only RESPONSE body when Creating new Mock

**Comment by ShykulaD** [comment]
Here is example

**Comment by ShykulaD** [comment]
![Screenshot 2021-05-18 at 09 04 53](https://user-images.githubusercontent.com/19273046/118599752-b4326880-b7b8-11eb-9d29-05cfbdb7270a.jpg)

**Comment by mukuljainx** [comment]
You can't add the request body here, API calls are mocked on the basis of URL only, everything else is ignored as of now and there is no plan to use `query parmas` or `body` for matching as they same as are params to a function call.
Later on, with the Mokku dashboard, you can provide a function for any URL where you will get the passed body as param there you can perform any operation and return back just like Express framework.

Why do want to add a body? different mocks according to the `body`?

**Comment by ShykulaD** [comment]
I want to **intercept** request and cause of this my only way is to send this request via UI (click button for example), than go to **Logs** section and find this request and **click Mock**. 
And next time when I click this button I can intercept request.
Am I right?

**Comment by ShykulaD** [comment]
Or Mokku is designed to Mock only Response?

**Comment by mukuljainx** [comment]
Yes, it is designed to mock response only ( and headers), you can assume it as a server running in Chrome.  In logs, you can see the body, query params because they are fetched from the current request to help the user, those are not saved with mocks.
