### ISSUE TITLE
Add possibilities to mock url with all ids

### ISSUE THREAD

**Issue by ledeneveugene** [mukuljainx/Mokku#51]
I call 2 methods when saving data:
1st  - POST /job - this method return job id(jobId).
2nd - POST /job/{jobId}/generate  - this method create task for generate job.

I don't know which jobId I going to get. I want to mock 2nd method for all jobIds. For example /job/*/generate
Can I do it now? If not, could you please implement it?

**Comment by mukuljainx** [comment]
Hi @ledeneveugene,

try using the `/job/:jobId/generate`, this should work for all `jobId` if it doesn't, please let me know!
