### ISSUE TITLE
Enabling mokku modifies the init.headers parameter of window.fetch()!

### ISSUE THREAD

**Issue by molhanec-work** [mukuljainx/Mokku#58]
Hello,

mokku is really great tool. 

I've just found an issue: when enabling mokku, it might modify the object passed as a second argument to `fetch()`.
Example: 
```
 const options = {
    headers: {
      Accept: 'application/json',
    }
  }

  console.log('before', options.headers)
  const response = await fetch(url, options)
  console.log('after', options.headers)
```
will show:
![image](https://user-images.githubusercontent.com/89903860/131638073-11486b69-19f5-4b2a-8a61-3af1abd1fa85.png)
i.e. the object was changed from a plain object to a Headers instance :-/
That means that any code which will access the options.headers like `Accept in options.headers` will fail when the Mokku is enabled.

**Comment by mukuljainx** [comment]
Hi @molhanec-work,

Thanks for reporting this. Just wants to confirm, this is happening even if that API is not mocked?

**Comment by molhanec-work** [comment]
Yes, it happens any time when I enable mocking in Mokku, without any mocks at all.

**Comment by mukuljainx** [comment]
@molhanec-work This bug can't be fixed right away, sorry for that. It will be addressed with [v2](https://github.com/mukuljainx/Mokku/discussions/60), the bug belongs to the engine which has a dependency on a library, I am working to re-write the whole thing and remove external dependencies.

**Comment by molhanec-work** [comment]
Thanks for the investigation 👍
