### ISSUE TITLE
Allow resizing of Mokku frames

### ISSUE THREAD

**Issue by cgraham-rs** [mukuljainx/Mokku#61]
As a user I want to manually resize the various frames in the Mokku UI.

In the `Mocks` tab there's a method/url frame on the left, and the mock detail frame on the right. Viewing on a 4k monitor at various scaling the mock detail is always a tiny fraction of the screen. However, that's the frame I need to use to edit the mocked data. 

![image](https://user-images.githubusercontent.com/87026636/132743218-d5399f77-2e9e-4e87-8e79-254c55a105bd.png)

![image](https://user-images.githubusercontent.com/87026636/132744124-91265725-9722-4fad-ba64-e298cd204437.png)

**Comment by mukuljainx** [comment]
Hi @cgraham-rs,

Thanks for the suggestion, pretty useful on big screens, will be implemented in the next major release.

**Comment by mukuljainx** [comment]
Added in v2.0.0
