### ISSUE TITLE
iFrame support?

### ISSUE THREAD

**Issue by gilesbutler** [mukuljainx/Mokku#62]
Hi,

Thanks for a great extension, am I right in assuming it doesn't support requests made from an iFrame?

I don't see them come through when I press record. The parent frames requests get recorded though.

Thanks

**Comment by mukuljainx** [comment]
Hi @gilesbutler,

Yup, it doesn't support the IFrame requests as of now.

**Comment by gilesbutler** [comment]
Ok thanks for letting me know @mukuljainx 👍

**Comment by gilesbutler** [comment]
Are you planning on adding support at any point?

**Comment by mukuljainx** [comment]
There is no plan as of now I will need to check if the chrome allows an extension to inject code in IFrame or not, if they do this will be picked after planned features for V2.

**Comment by gilesbutler** [comment]
Ok great, thanks @mukuljainx

**Comment by Luiz-Not** [comment]
I need this
