### ISSUE TITLE
Tips `Mokku not available on this url.` when DevTools is undocked into separate window

### ISSUE THREAD

**Issue by BenzLeung** [mukuljainx/Mokku#67]
When DevTools is undocked into separate window, Mokku panel always tips `Mokku not available on this url.`

![image](https://user-images.githubusercontent.com/2764768/144406580-6786d0c2-7c1b-46fd-90b9-7c9ee2466f1b.png)

It only works properly when I dock it inside the tab page.

![image](https://user-images.githubusercontent.com/2764768/144407355-c9f676a3-e25d-4f98-bc50-213a6b98fb4b.png)

My OS: macOS big sur 11.6.1
My Browser: Chrome 96.0.4664.55 (Stable) (x86_64)

**Comment by mukuljainx** [comment]
Hi @BenzLeung, thanks for reporting this, I will try to get around in next release. For now, can you try opening the Mokku first then separate the windows?

**Comment by BenzLeung** [comment]
I tried.

Mokku works fine.

It is the only way that Mokku to work in the separate window.

Sincerely look forward to your next release.

**Comment by mukuljainx** [comment]
sure! It will be included.

**Comment by agagnon2** [comment]
This is still problematic today! Just happen to me with an external devtools window. I closed the dev tooling window, opened it inside the chrome browser and it then works. I was then able to undock it to a separate window

**Comment by sarathjasrin** [comment]
Still, it's not fixed.
