### ISSUE TITLE
Request: feature to drop request entirely

### ISSUE THREAD

**Issue by cgraham-rs** [mukuljainx/Mokku#89]
As a user I want to completely drop a request and not provide any response at all.

**Comment by mukuljainx** [comment]
Hi @cgraham-rs , do mean no response body just status?

**Comment by cgraham-rs** [comment]
I mean completely drop it. No response is returned. This is the one potential error condition the proxy currently cannot handle from what I can tell. 

It can currently be configured to return error codes and/or delay responses, but not completely drop them.

I believe in Charles Proxy it's called "Abort" and in Burp it's called "Drop".

**Comment by mukuljainx** [comment]
Marking `status` as `0` drops the request.
